project:
  type: website
  output-dir: docs

website:
  title: "Amanda Herbst"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog.qmd
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/amanda-herbst
      - icon: github
        href: https://github.com/amandaherbst
      - icon: envelope
        href: mailto::aherbst@ucsb.edu

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    page-layout: full
    
editor: source



